- src/main/java/com/finalProject/Back/aspect/ValidAspect.java
- src/main/java/com/finalProject/Back/aspect/annotation/ValidAop.java
> 24-10-08 Env: "aop 구현"

- src/main/java/com/finalProject/Back/aspect/ValidAspect.java
- src/main/java/com/finalProject/Back/config/BCryptConfig.java
- src/main/java/com/finalProject/Back/config/OAuth2Config.java
- src/main/java/com/finalProject/Back/config/SecurityConfig.java
- src/main/java/com/finalProject/Back/config/WebMvcConfig.java
BCryptConfg
OAuth2Config
SecurityConfig
WebMvcConfig
> 24-10-08 Env: "config 구현"

- .gitignore
- pom.xml
- src/main/resources/application.yml
mvc, mybatis, mail, user default img, MySQL, OAuth2, JWT
> Env: yml 파일 세팅

- src/main/java/com/finalProject/Back/aspect/ValidAspect.java
- src/main/java/com/finalProject/Back/config/SecurityConfig.java
- src/main/java/com/finalProject/Back/controller/BoardController.java
- src/main/java/com/finalProject/Back/dto/request/ReqBoardDto.java
- src/main/java/com/finalProject/Back/entity/Board.java
- src/main/java/com/finalProject/Back/repository/BoardMapper.java
- src/main/java/com/finalProject/Back/security/principal/PrincipalUser.java
- src/main/java/com/finalProject/Back/service/BoardService.java
- src/main/resources/application.yml
- src/main/resources/mappers/board.xml
게시글 작성 기능을 구현하기 위해controller, service, mapper, entity, dto를 작성하였음.
> Feat: 게시글 작성 기능 구현

- src/main/java/com/finalProject/Back/aspect/ValidAspect.java
- src/main/java/com/finalProject/Back/config/SecurityConfig.java
- src/main/java/com/finalProject/Back/controller/BoardController.java
- src/main/java/com/finalProject/Back/controller/UserController.java
- src/main/java/com/finalProject/Back/dto/request/ReqBoardDto.java
- src/main/java/com/finalProject/Back/dto/request/ReqSignupDto.java
- src/main/java/com/finalProject/Back/dto/response/RespSignupDto.java
- src/main/java/com/finalProject/Back/entity/Board.java
- src/main/java/com/finalProject/Back/entity/Role.java
- src/main/java/com/finalProject/Back/entity/User.java
- src/main/java/com/finalProject/Back/entity/UserRoles.java
- src/main/java/com/finalProject/Back/repository/BoardMapper.java
- src/main/java/com/finalProject/Back/repository/UserMapper.java
- src/main/java/com/finalProject/Back/security/principal/PrincipalUser.java
- src/main/java/com/finalProject/Back/service/BoardService.java
- src/main/java/com/finalProject/Back/service/UserService.java
- src/main/resources/application.yml
- src/main/resources/mappers/board.xml
- src/main/resources/mappers/user.xml
> Feat: "회원가입 작업"

- src/main/java/com/finalProject/Back/controller/BoardController.java
- src/main/java/com/finalProject/Back/dto/request/ReqBoardDto.java
- src/main/java/com/finalProject/Back/dto/response/RespBoardDto.java
- src/main/java/com/finalProject/Back/entity/board/Board.java
- src/main/java/com/finalProject/Back/entity/board/BoardList.java
- src/main/java/com/finalProject/Back/repository/BoardMapper.java
- src/main/java/com/finalProject/Back/service/BoardService.java
- src/main/resources/mappers/board.xml
> Feat: 전체 게시글 가져오기

- src/main/java/com/finalProject/Back/config/SecurityConfig.java
- src/main/java/com/finalProject/Back/dto/request/ReqSignupDto.java
- src/main/java/com/finalProject/Back/entity/User.java
- src/main/resources/application.yml
- src/main/resources/mappers/user.xml
> "Feat" : "회원가입 추가"

- src/main/java/com/finalProject/Back/controller/BoardController.java
- src/main/resources/application.yml
- src/main/resources/mappers/user.xml
> Fix: 유저 default 프로필 이미지 오류 수정

- src/main/java/com/finalProject/Back/config/SecurityConfig.java
- src/main/java/com/finalProject/Back/controller/CafeController.java
- src/main/java/com/finalProject/Back/dto/request/ReqCafeDto.java
- src/main/java/com/finalProject/Back/entity/Cafe.java
- src/main/java/com/finalProject/Back/repository/CafeMapper.java
- src/main/java/com/finalProject/Back/service/CafeService.java
- src/main/resources/mappers/cafe.xml
백엔드 카페 추가로직 완성
예시 카페 50개 DB에 추가
> 24-10-10 Feat: "백엔드 카페 추가기능"

- src/main/java/com/finalProject/Back/controller/BoardController.java
- src/main/java/com/finalProject/Back/dto/response/RespBoardDto.java
- src/main/java/com/finalProject/Back/entity/board/Board.java
- src/main/java/com/finalProject/Back/exception/NotFoundBoardException.java
- src/main/java/com/finalProject/Back/repository/BoardMapper.java
- src/main/java/com/finalProject/Back/service/BoardService.java
- src/main/resources/mappers/board.xml
> Feat: 게시글 상세 페이지 데이터를 들고오기 위한 백엔드 로직 구현

- src/main/java/com/finalProject/Back/controller/BoardController.java
- src/main/java/com/finalProject/Back/dto/request/ReqBoardDto.java
- src/main/java/com/finalProject/Back/repository/BoardMapper.java
- src/main/java/com/finalProject/Back/service/BoardService.java
- src/main/resources/mappers/board.xml
> Feat: 게시글 수정 기능 구현

- src/main/java/com/finalProject/Back/controller/CafeController.java
- src/main/java/com/finalProject/Back/dto/request/ReqGetCafeDto.java
- src/main/java/com/finalProject/Back/dto/response/RespCafeListDto.java
- src/main/java/com/finalProject/Back/entity/Cafe.java
- src/main/java/com/finalProject/Back/repository/CafeMapper.java
- src/main/java/com/finalProject/Back/service/CafeService.java
- src/main/resources/mappers/cafe.xml
> : 24-10-10 Feat: "카테고리별 카페 불러오기"

- src/main/java/com/finalProject/Back/controller/CafeController.java
- src/main/java/com/finalProject/Back/repository/CafeMapper.java
- src/main/java/com/finalProject/Back/service/CafeService.java
- src/main/resources/mappers/cafe.xml
> 24-10-11 Feat: "카페 검색기능 추가"

- src/main/java/com/finalProject/Back/controller/BoardController.java
- src/main/java/com/finalProject/Back/dto/request/ReqBoardDto.java
- src/main/java/com/finalProject/Back/entity/board/BoardList.java
- src/main/java/com/finalProject/Back/repository/BoardMapper.java
- src/main/java/com/finalProject/Back/service/BoardService.java
- src/main/resources/mappers/board.xml
- page, limit, searchFilter, inputValue를 params로 받아서 전체, 제목으로 검색하여 리스트를 뽑을수 있게 구현했음. 
- 작성자로 검색은 나중에 구현 예정
> Feat: 게시글 검색 기능 구현을 위한 코드 작성

- src/main/java/com/finalProject/Back/config/SecurityConfig.java
- src/main/java/com/finalProject/Back/controller/CommentController.java
- src/main/java/com/finalProject/Back/dto/request/ReqCommentDto.java
- src/main/java/com/finalProject/Back/dto/response/RespCommentDto.java
- src/main/java/com/finalProject/Back/entity/Comment.java
- src/main/java/com/finalProject/Back/repository/CommentMapper.java
- src/main/java/com/finalProject/Back/service/CommentService.java
- src/main/resources/mappers/comment.xml
- 댓글을 작성하면 comment 테이블에 저장됨.
- front-end에서 userQuery를 통해 해당 게시글에 대한 모든 댓글을 요청하면 backend에서 해당 게시글에 대한 모든 댓글들을 리스트 형태로 반환.
> Feat: 댓글 작성 기능 구현

- src/main/java/com/finalProject/Back/controller/CommentController.java
- src/main/java/com/finalProject/Back/dto/request/ReqCommentDto.java
- src/main/java/com/finalProject/Back/exception/AccessDeniedException.java
- src/main/java/com/finalProject/Back/repository/CommentMapper.java
- src/main/java/com/finalProject/Back/service/CommentService.java
- src/main/resources/mappers/comment.xml
- commentId로 해당하는 댓글을 찾아 댓글의 content 수정
> Feat: 댓글 수정 기능 구현

- src/main/java/com/finalProject/Back/controller/CommentController.java
- src/main/java/com/finalProject/Back/repository/CommentMapper.java
- src/main/java/com/finalProject/Back/service/CommentService.java
- src/main/resources/mappers/comment.xml
commentId로 해당 댓글을 찾아 삭제함, 답글이 있는 댓글일 경우 답글까지 모두 삭제하도록 query문 작성
> Feat: 댓글 삭제 기능 구현

- src/main/java/com/finalProject/Back/config/SecurityConfig.java
- src/main/java/com/finalProject/Back/controller/OwnerController.java
- src/main/java/com/finalProject/Back/dto/response/RespGetOwnerDto.java
- src/main/java/com/finalProject/Back/dto/response/RespGetUserDto.java
- src/main/java/com/finalProject/Back/repository/OwnerMapper.java
- src/main/java/com/finalProject/Back/service/OwnerService.java
- src/main/resources/mappers/Owner.xml
> 24-10-21 Feat: "매니저페이지"

- src/main/java/com/finalProject/Back/controller/OwnerController.java
- src/main/java/com/finalProject/Back/repository/OwnerMapper.java
- src/main/java/com/finalProject/Back/service/OwnerService.java
- src/main/resources/mappers/Owner.xml
> 24-10-21 Feat: "관리자 페이지-점포 관리"

- src/main/java/com/finalProject/Back/controller/OwnerController.java
- src/main/java/com/finalProject/Back/repository/BoardMapper.java
- src/main/java/com/finalProject/Back/repository/CommentMapper.java
- src/main/java/com/finalProject/Back/repository/OwnerMapper.java
- src/main/java/com/finalProject/Back/repository/ReviewMapper.java
- src/main/java/com/finalProject/Back/service/OwnerService.java
- src/main/resources/mappers/board.xml
- src/main/resources/mappers/comment.xml
- src/main/resources/mappers/review.xml
> 24-10-22 Feat: "삭제"

- src/main/java/com/finalProject/Back/controller/OwnerController.java
- src/main/java/com/finalProject/Back/dto/response/RespBoardInfoDto.java
- src/main/java/com/finalProject/Back/dto/response/RespCommentInfoDto.java
- src/main/java/com/finalProject/Back/dto/response/RespInfoDto.java
- src/main/java/com/finalProject/Back/dto/response/RespReviewInfoDto.java
- src/main/java/com/finalProject/Back/dto/response/RespUserInfoDto.java
- src/main/java/com/finalProject/Back/entity/User.java
- src/main/java/com/finalProject/Back/repository/BoardMapper.java
- src/main/java/com/finalProject/Back/repository/CommentMapper.java
- src/main/java/com/finalProject/Back/repository/ReviewMapper.java
- src/main/java/com/finalProject/Back/repository/UserMapper.java
- src/main/java/com/finalProject/Back/service/OwnerService.java
- src/main/resources/mappers/board.xml
- src/main/resources/mappers/comment.xml
- src/main/resources/mappers/review.xml
- src/main/resources/mappers/user.xml
> 24-10-23 Feat: "유저 정보 조회"

- src/main/java/com/finalProject/Back/config/SecurityConfig.java
- src/main/java/com/finalProject/Back/controller/ReportController.java
- src/main/java/com/finalProject/Back/dto/request/ReqReportDto.java
- src/main/java/com/finalProject/Back/dto/response/RespReportDto.java
- src/main/java/com/finalProject/Back/entity/Report.java
- src/main/java/com/finalProject/Back/repository/ReportMapper.java
- src/main/java/com/finalProject/Back/service/ReportService.java
- src/main/resources/mappers/report.xml
> 24-11-09 Feat:"신고기능"
